full-stack-project/resources/cdns/file_upload_demo/config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'
  resources :tweets

  namespace :api, defaults: {format: :json} do
    resources :tweets, only: [:index, :create, :show]
  end

end

full-stack-project/resources/cdns/file_upload_demo/app/models/country.rb
# == Schema Information
#
# Table name: countries
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime
#  updated_at :datetime
#

class Country < ActiveRecord::Base
  has_many(
    :users,
    class_name: "User",
    foreign_key: :country_id,
    primary_key: :id
  )

  has_many(
    :tweets,
    through: :users,
    source: :tweets
  )
end

full-stack-project/resources/cdns/file_upload_demo/app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id         :integer          not null, primary key
#  body       :string           not null
#  created_at :datetime
#  updated_at :datetime
#  author_id  :integer          not null
#

class Tweet < ActiveRecord::Base
  validates :body, presence: true
  validates :author_id, presence: true

  has_attached_file :image, default_url: "corgi.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id
  )

  has_one(
    :country,
    through: :author,
    source: :country
  )
end

full-stack-project/resources/cdns/file_upload_demo/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  email      :string           not null
#  created_at :datetime
#  updated_at :datetime
#  country_id :integer          not null
#

class User < ActiveRecord::Base
  belongs_to(
    :country,
    class_name: "Country",
    foreign_key: :country_id,
    primary_key: :id
  )

  has_many(
    :tweets,
    class_name: "Tweet",
    foreign_key: :author_id,
    primary_key: :id
  )

  def self.usernames_and_tweet_counts_n_plus_one_version
    tweet_counts = {}

    User.all.each do |user|
      tweet_counts[user.name] = user.tweets.length
    end

    tweet_counts
  end

  def self.usernames_and_tweet_counts_two_queries_version
    tweet_counts = {}

    User.includes(:tweets).all.each do |user|
      tweet_counts[user.name] = user.tweets.length
    end

    tweet_counts
  end

  def self.usernames_and_tweet_counts
    tweet_counts = {}

    users = User
      .select("users.*, COUNT(tweets.id) AS tweet_count")
      .joins(:tweets)
      .group(:id)

    users.each do |user|
      tweet_counts[user.name] = user.tweet_count
    end

    tweet_counts

  end

end

full-stack-project/resources/cdns/file_upload_demo/app/controllers/api/tweets_controller.rb
class Api::TweetsController < ApplicationController

  def index
    @tweets = Tweet.includes(:author).all.order(created_at: :desc)
  end

  def create
    @tweet = User.find_by(name: "Fred").tweets.create(tweet_params)
    render :show
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  private

  def tweet_params
    params.require(:tweet).permit(:body, :image)
  end
end

full-stack-project/resources/cdns/file_upload_demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

full-stack-project/resources/cdns/file_upload_demo/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root
  end
end

full-stack-project/resources/cdns/file_upload_demo/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
    render :show
  end

  def new
    @tweet = Tweet.new
    render :new
  end

  def create
    @tweet = Tweet.new(tweet_params)

    if @tweet.save
      redirect_to tweet_url(@tweet.id)
    else
      render :new
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
    render :edit
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweet_url(@tweet.id)
    else
      render :edit
    end

  end

  def destroy
    Tweet.find(params[:id]).destroy
    redirect_to tweets_url
  end



  private

  def tweet_params
    params.require(:tweet).permit(:body, :author_id)
  end




end


# NAMESPACING
# Namespace your form data! ie tweet[body]
# {"tweet" => {
# "body" => "Ain't Rails Grand",
# "author_id" => 8
# }
#}

# STRONG PARAMS
# Use strong params! Tweet.new(params[:tweet]) == security problem.
# famous example that triggered the move to strong_params: the github hack!
# someone set his own user_id on Github to that of an admin.
# check it out here: https://gist.github.com/peternixey/1978249
# strong_params are only relevant for non-GET requests (where you're updating db)
# you have to specifically whitelist params you want to allow

# WHAT IS PARAMS ANYWAY
# Params: a method that Rails gives you
# returns a "hash-like" object that you can index into just
# like a hash. e.g., to pull out id from params you'll do `params[:id]`

full-stack-project/resources/cdns/file_upload_demo/app/helpers/api/tweets_helper.rb
module Api::TweetsHelper
end

full-stack-project/resources/cdns/file_upload_demo/app/helpers/application_helper.rb
module ApplicationHelper
end

full-stack-project/resources/cdns/file_upload_demo/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

full-stack-project/resources/cdns/file_upload_demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html>

full-stack-project/resources/cdns/file_upload_demo/app/views/tweets/_form.html.erb
<ul>
  <% tweet.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

<% if tweet.persisted? %>
  <% url = tweet_url(tweet.id) %>
  <% button_text = "Update tweet!" %>
<% else %>
  <% url = tweets_url %>
  <% button_text = "Create tweet!" %>
<% end %>

<form action="<%= url %>" method="POST">
  <% if tweet.persisted? %>
    <input type="hidden" name="_method" value="PUT">
  <% end %>

  <label for="tweet_body">Tweet Body</label>
  <input type="text" name="tweet[body]" value="<%= tweet.body %>" id="tweet_body">

  <label>
    Author ID
    <input type="text" name="tweet[author_id]" value="<%= tweet.author_id %>">
  </label>

  <input type="submit" value="<%= button_text %>">
</form>

full-stack-project/resources/cdns/file_upload_demo/app/views/tweets/edit.html.erb
<h1>Edit your tweet!</h1>
<%= render "form", tweet: @tweet %>

<a href="<%= tweets_url %>">Back to Tweets</a>

full-stack-project/resources/cdns/file_upload_demo/app/views/tweets/index.html.erb
  <h<%= 1 %>>
    All the tweets
  </h<%= 1 %>>
  <a href="<%= new_tweet_url  %>">New Tweet</a>


<ul>
  <% @tweets.each do |tweet| %>
    <li>
      <a href="<%= tweet_url(tweet.id) %>">
        <%= tweet.body %>
      </a>
    </li>
  <% end %>
</ul>

full-stack-project/resources/cdns/file_upload_demo/app/views/tweets/new.html.erb
<h1>Make a new tweet!</h1>
<%= render "form", tweet: @tweet %>

<a href="<%= tweets_url %>">Back to Tweets</a>

full-stack-project/resources/cdns/file_upload_demo/app/views/tweets/show.html.erb
<h1><%= @tweet.body %></h1>
<h3><%= @tweet.author.name %></h3>

<form action="<%= tweet_url(@tweet.id) %>" method="POST">
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit"  value="Destroy tweet">
</form>

<a href="<%= tweets_url %>">Back to Tweets</a>
<a href="<%= edit_tweet_url(@tweet.id) %>">Edit</a>