javascript/projects/ajax_twitter/solution/config/routes.rb
AjaxTwitter::Application.routes.draw do
  resource :feed, only: [:show]
  resource :session, only: [:create, :destroy, :new]
  resources :tweets, only: [:create, :index]
  resources :users, only: [:create, :new, :show] do
    get "search", on: :collection

    resource :follow, only: [:create, :destroy]
  end

  root to: redirect("/feed")
end

javascript/projects/ajax_twitter/solution/app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :require_logged_in!

  LIMIT = 20

  def show
    @feed_tweets =
      current_user.feed_tweets(LIMIT, params[:max_created_at]).includes(:user, :mentions)
    respond_to do |format|
      format.html { render :show }
      format.json { render :show }
    end
  end
end

javascript/projects/ajax_twitter/solution/app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :require_logged_in!

  def create
    # simulate latency
    sleep(1)

    @follow = current_user.out_follows.create!(followee_id: params[:user_id])

    respond_to do |format|
      format.html { redirect_to request.referrer }
      format.json { render :show }
    end
  end

  def destroy
    # simulate latency
    sleep(1)

    @follow = current_user.out_follows.find_by(followee_id: params[:user_id])
    @follow.destroy!

    respond_to do |format|
      format.html { redirect_to request.referrer }
      format.json { render :show }
    end
  end
end

javascript/projects/ajax_twitter/solution/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_logged_in!

  def create
    # simulate latency
    sleep(1)

    @tweet = current_user.tweets.build(tweet_params)

    if @tweet.save
      respond_to do |format|
        format.html { redirect_to request.referrer }
        format.json { render :show }
      end
    else
      # Lazy: even respond with JSON to invalid HTML request.
      render json: @tweet.errors.full_messages, status: 422
    end
  end

  def index
    @tweets = Tweet.all.includes(:user, :mentioned_users)
    render :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:content, mentioned_user_ids: [])
  end
end

javascript/projects/ajax_twitter/solution/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_not_logged_in!, only: [:create, :new]
  before_action :require_logged_in!, only: [:show]

  def create
    # sign up the user
    @user = User.new(user_params)
    if @user.save
      # redirect them to the new user's show page
      log_in!(@user)
      redirect_to feed_url
    else
      # input didn't pass validation; re-render sign up form.
      render :new
    end
  end

  def new
    # present form for signup
    @user = User.new # dummy user object
    render :new
  end

  def show
    if current_user.nil?
      # let them log in
      redirect_to new_session_url
      return
    end

    @user = User.includes(tweets: :mentioned_users).find(params[:id])
    render :show
  end

  def search
    if params[:query].present?
      @users = User.where("username ~ ?", params[:query]).includes(:out_follows)
    else
      @users = User.none
    end

    respond_to do |format|
      format.html { render :search }
      format.json { render :search }
    end
  end

  protected
  def user_params
    self.params.require(:user).permit(:username, :password)
  end
end

javascript/projects/ajax_twitter/solution/app/views/feeds/show.html.erb
<h1>Welcome <%= current_user.username %>!</h1>
<div class="main-feed">
  <div class="infinite-tweets">
    <h3>Your Feed!</h3>
    <script type="text/template">
      <%% tweets.forEach(function (tweet) { %>
        <li>
          <%%= tweet.content %>
          -- <a href="<%%= "/users/" + tweet.user.id %>"><%%= tweet.user.username %></a>
          -- <%%= tweet.created_at %>
          <ul>
            <%% tweet.mentions.forEach(function (mention) { %>
              <li>
                <a href="<%%= "/users/" + mention.user_id %>"><%%= mention.user.username %></a>
              </li>
            <%% }); %>
          </ul>
        </li>
      <%% }); %>
    </script>

    <ul class="tweets" id="feed"></ul>

    <a href="javascript:void(0)" class="fetch-more">Fetch more tweets!</a>
  </div>

  <div class="tweet-form">
    <%= render "tweets/form", tweets_ul: "#feed" %>
  </div>
</div>

javascript/projects/ajax_twitter/solution/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="http://underscorejs.org/underscore-min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>

<ul>
  <li><%= link_to "Feed", feed_url %></li>
  <li><%= link_to "User Search", search_users_url %></li>
</ul>

<% if current_user %>
  <form action="/session" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">

    <input type="submit" value="Logout!">
  </form>
<% end %>

<%= yield %>

</body>
</html>